# Generated by Django 4.2 on 2025-09-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
